# Generated by Django 5.0.3 on 2024-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kin_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin',
            name='relationship',
            field=models.CharField(default='', max_length=50),
        ),
    ]
