# Generated by Django 5.0.3 on 2024-04-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_student_department_student_level'),
        ('landing', '0002_rename_level_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.session'),
        ),
    ]
