# Generated by Django 5.0.3 on 2024-04-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='level',
            new_name='title',
        ),
    ]
